from typing import Protocol
from uuid import UUID

from app.domain.entities import Document, Library, ScoredChunk

# Protocol (structural typing), not ABC — infra classes satisfy these by shape alone, no
# explicit inheritance needed. Same Dependency Inversion benefit, less ceremony.


class LibraryRepositoryPort(Protocol):
    def create(self, **fields) -> Library: ...

    def get(self, library_id: UUID) -> Library | None: ...

    def list(self, limit: int, offset: int, sort: str) -> list[Library]: ...

    def count(self) -> int: ...

    def delete(self, library_id: UUID) -> None: ...

    def increment_counts(self, library_id: UUID, document_delta: int, chunk_delta: int) -> None: ...


class DocumentRepositoryPort(Protocol):
    def create(self, **fields) -> Document: ...

    def get(self, document_id: UUID) -> Document | None: ...

    def list_for_library(self, library_id: UUID, limit: int, offset: int, sort: str) -> list[Document]: ...

    def count_for_library(self, library_id: UUID) -> int: ...

    def update_status(self, document_id: UUID, status: str, ingested_at=None) -> Document: ...


class ChunkRepositoryPort(Protocol):
    def bulk_create(self, document_id: UUID, library_id: UUID, chunks: list[tuple[int, str, list[float]]]) -> None: ...

    def similarity_search(self, library_id: UUID, query_embedding: list[float], top_k: int) -> list[ScoredChunk]: ...
