from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from api.domain.entities import (
    Application,
    ApplicationApiKey,
    ApplicationOAuthClient,
    AuthorizationCode,
    Category,
    Chunk,
    Document,
    EmbeddingProviderConfig,
    EmbeddingSettings,
    Identity,
    IngestionJob,
    MCPSettings,
    OrgMember,
    Organization,
    Profile,
    Query,
    QueryResult,
    RefreshToken,
    ScoredChunk,
    Shelf,
    Source,
    Tag,
)

# Protocol (structural typing), not ABC — infra classes satisfy these by shape alone, no
# explicit inheritance needed. Same Dependency Inversion benefit, less ceremony.


class DocumentRepositoryPort(Protocol):
    def create(self, **fields) -> Document: ...

    def get(self, document_id: UUID) -> Document | None: ...

    def list_by_ids(self, document_ids: list[UUID]) -> list[Document]: ...

    def list_for_org(
        self,
        org_id: UUID,
        limit: int,
        offset: int,
        sort: str,
        category_id: UUID | None = None,
        shelf_id: UUID | None = None,
        document_type: str | None = None,
    ) -> list[Document]: ...

    def count_for_org(
        self,
        org_id: UUID,
        category_id: UUID | None = None,
        shelf_id: UUID | None = None,
        document_type: str | None = None,
    ) -> int: ...

    def update_status(
        self,
        document_id: UUID,
        status: str,
        indexed_at=None,
        error_message: str | None = None,
        chunk_count: int | None = None,
    ) -> Document: ...

    def get_raw_bytes(self, document_id: UUID) -> bytes | None: ...

    def rename(self, document_id: UUID, new_title: str) -> Document: ...

    def update_metadata(self, document_id: UUID, category_id: UUID | None, document_type: str) -> Document: ...

    def delete(self, document_id: UUID) -> None: ...


class ChunkRepositoryPort(Protocol):
    def bulk_create(
        self,
        document_id: UUID,
        org_id: UUID,
        embedding_model_id: UUID,
        chunks: list[tuple[int, str, int, list[float]]],
    ) -> None: ...

    def similarity_search(
        self, org_id: UUID, query_embedding: list[float], top_k: int, category_id: UUID | None = None
    ) -> list[ScoredChunk]: ...

    def sparse_search(
        self, org_id: UUID, query_text: str, top_k: int, category_id: UUID | None = None
    ) -> list[ScoredChunk]: ...

    def count_for_document(self, document_id: UUID) -> int: ...

    def count_all(self) -> int: ...

    def count_for_org(self, org_id: UUID) -> int: ...

    def list_for_document(self, document_id: UUID, limit: int, offset: int) -> list[Chunk]: ...

    def resize_embedding_column(self, dimensions: int) -> None: ...


class EmbeddingSettingsRepositoryPort(Protocol):
    """Read-only view of whichever provider is currently active — the only thing ingestion and
    retrieval ever need. Writes go through EmbeddingProviderSettingsRepositoryPort instead, since
    "active" now means one row among several per-provider configs, not a single global row."""

    def get(self, org_id: UUID) -> EmbeddingSettings | None: ...


class EmbeddingProviderSettingsRepositoryPort(Protocol):
    def list(self, org_id: UUID) -> list[EmbeddingProviderConfig]: ...

    def get(self, org_id: UUID, provider: str) -> EmbeddingProviderConfig | None: ...

    def upsert_config(
        self,
        org_id: UUID,
        provider: str,
        model: str,
        api_key: str | None,
        base_url: str | None,
        dimensions: int,
        chunk_size: int,
        chunk_overlap: int,
    ) -> EmbeddingProviderConfig: ...

    def set_enabled(self, org_id: UUID, provider: str, enabled: bool) -> EmbeddingProviderConfig: ...


class OrganizationRepositoryPort(Protocol):
    def create(self, name: str, slug: str, **fields) -> Organization: ...

    def get(self, org_id: UUID) -> Organization | None: ...

    def get_by_slug(self, slug: str) -> Organization | None: ...

    def update(self, org_id: UUID, name: str, description: str | None) -> Organization: ...

    def list(self) -> list[Organization]: ...


class CategoryRepositoryPort(Protocol):
    def create(self, org_id: UUID, name: str, slug: str, **fields) -> Category: ...

    def get(self, category_id: UUID) -> Category | None: ...

    def update(self, category_id: UUID, name: str, description: str | None) -> Category: ...

    def list_by_org(self, org_id: UUID) -> list[Category]: ...

    def delete(self, category_id: UUID) -> None: ...

    # Router RAG: routes a category-less query to the most relevant category by cosine similarity
    # between the query embedding and each category's cached description_embedding.
    def set_description_embedding(self, category_id: UUID, embedding: list[float] | None) -> None: ...

    def list_all_with_description(self, org_id: UUID) -> list[Category]: ...

    def clear_all_description_embeddings(self, org_id: UUID) -> None: ...

    def search_by_description_similarity(
        self, org_id: UUID, query_embedding: list[float], top_n: int, min_similarity: float
    ) -> list[tuple[Category, float]]: ...


class TagRepositoryPort(Protocol):
    def create(self, org_id: UUID, name: str, **fields) -> Tag: ...

    def get(self, tag_id: UUID) -> Tag | None: ...

    def list_by_org(self, org_id: UUID) -> list[Tag]: ...

    def tag_document(self, document_id: UUID, tag_id: UUID) -> None: ...

    def untag_document(self, document_id: UUID, tag_id: UUID) -> None: ...

    def list_for_document(self, document_id: UUID) -> list[Tag]: ...


class QueryRepositoryPort(Protocol):
    def create(self, org_id: UUID, query_text: str, **fields) -> Query: ...

    def record_results(self, query_id: UUID, results: list[tuple[UUID, int, float]]) -> None: ...

    def list_by_org(self, org_id: UUID, limit: int, offset: int) -> list[Query]: ...

    def rollback(self) -> None: ...

    def count_since(self, org_id: UUID, since: datetime) -> int: ...

    def avg_latency_since(self, org_id: UUID, since: datetime) -> float | None: ...

    def most_retrieved_documents(self, org_id: UUID, limit: int) -> list[tuple[UUID, str, int, float]]: ...

    def retrieval_stats_for_document(self, document_id: UUID) -> tuple[int, float | None]: ...


class ShelfRepositoryPort(Protocol):
    def create(self, org_id: UUID, name: str, slug: str, **fields) -> Shelf: ...

    def get(self, shelf_id: UUID) -> Shelf | None: ...

    def update(self, shelf_id: UUID, name: str, description: str | None) -> Shelf: ...

    def delete(self, shelf_id: UUID) -> None: ...

    def list_by_org(self, org_id: UUID) -> list[Shelf]: ...

    def get_default_for_org(self, org_id: UUID) -> Shelf | None: ...

    def count_documents(self, shelf_id: UUID) -> int: ...

    def count_members(self, shelf_id: UUID) -> int: ...

    def add_document(self, document_id: UUID, shelf_id: UUID) -> None: ...

    def remove_document(self, document_id: UUID, shelf_id: UUID) -> None: ...

    def list_shelves_for_document(self, document_id: UUID) -> list[Shelf]: ...

    def grant_user_access(self, user_id: UUID, shelf_id: UUID, granted_by: UUID | None) -> None: ...

    def revoke_user_access(self, user_id: UUID, shelf_id: UUID) -> None: ...

    def list_accessible_shelf_ids(self, user_id: UUID) -> list[UUID]: ...


class SourceRepositoryPort(Protocol):
    def create(self, org_id: UUID, type: str, name: str, **fields) -> Source: ...

    def get(self, source_id: UUID) -> Source | None: ...

    def list_by_org(self, org_id: UUID) -> list[Source]: ...


class IngestionJobRepositoryPort(Protocol):
    def create(self, org_id: UUID, type: str, **fields) -> IngestionJob: ...

    def get(self, job_id: UUID) -> IngestionJob | None: ...

    def list_by_org(self, org_id: UUID, limit: int, offset: int) -> list[IngestionJob]: ...

    def update_status(self, job_id: UUID, status: str, **fields) -> IngestionJob: ...


class IdentityRepositoryPort(Protocol):
    def get(self) -> Identity | None: ...

    def get_by_id(self, identity_id: UUID) -> Identity | None: ...

    def get_by_email(self, email: str) -> Identity | None: ...

    def create(self, email: str, password_hash: str, *, name: str, must_change_password: bool = True) -> Identity: ...

    def update_password(self, identity_id: UUID, password_hash: str) -> None: ...


class OrgMemberRepositoryPort(Protocol):
    def create(self, org_id: UUID, identity_id: UUID, profile_id: UUID, *, invited_by: UUID | None = None) -> OrgMember: ...

    def get(self, org_id: UUID, identity_id: UUID) -> OrgMember | None: ...

    def list_for_identity(self, identity_id: UUID) -> list[OrgMember]: ...

    def list_for_org(self, org_id: UUID) -> list[OrgMember]: ...

    def update_profile(self, org_id: UUID, identity_id: UUID, profile_id: UUID) -> OrgMember: ...

    def delete(self, org_id: UUID, identity_id: UUID) -> None: ...


class IdentityVerifierPort(Protocol):
    """The swap seam: today backed by local password verification
    (PasswordIdentityVerifier), later swappable for real SSO/social login — callers only ever
    depend on this Protocol, never the concrete verifier."""

    def verify(self, email: str, password: str) -> Identity | None: ...


class ApplicationRepositoryPort(Protocol):
    def create(self, org_id: UUID, name: str, auth_method: str, service_identity_id: UUID, **fields) -> Application: ...

    def get(self, application_id: UUID) -> Application | None: ...

    def list_by_org(self, org_id: UUID) -> list[Application]: ...

    def update(self, application_id: UUID, name: str, description: str | None) -> Application: ...

    def revoke(self, application_id: UUID, revoked_by: UUID) -> Application: ...

    def delete(self, application_id: UUID) -> None: ...

    def set_scopes(self, application_id: UUID, scopes: list[str], granted_by: UUID | None) -> None: ...

    def list_scopes(self, application_id: UUID) -> list[str]: ...


class MCPSettingsRepositoryPort(Protocol):
    def get(self, org_id: UUID) -> MCPSettings | None: ...

    def upsert(
        self,
        org_id: UUID,
        rag_read_enabled: bool,
        object_read_enabled: bool,
        object_write_enabled: bool,
        modified_by: UUID | None,
    ) -> MCPSettings: ...


class ApplicationApiKeyRepositoryPort(Protocol):
    def create(self, application_id: UUID, key_hash: str, key_prefix: str) -> ApplicationApiKey: ...

    def get_by_key_hash(self, key_hash: str) -> ApplicationApiKey | None: ...

    def rotate(self, application_id: UUID, key_hash: str, key_prefix: str) -> ApplicationApiKey: ...

    def touch_last_used(self, application_id: UUID) -> None: ...


class ApplicationOAuthClientRepositoryPort(Protocol):
    def create(
        self, application_id: UUID, client_secret_hash: str | None, redirect_uris: list[str]
    ) -> ApplicationOAuthClient: ...

    def get_by_application(self, application_id: UUID) -> ApplicationOAuthClient | None: ...

    def rotate(self, application_id: UUID, client_secret_hash: str) -> ApplicationOAuthClient: ...


class AuthorizationCodeRepositoryPort(Protocol):
    def create(self, application_id: UUID, org_id: UUID, identity_id: UUID, **fields) -> AuthorizationCode: ...

    def get_by_code_hash(self, code_hash: str) -> AuthorizationCode | None: ...

    def mark_consumed(self, authorization_code_id: UUID) -> None: ...


class RefreshTokenRepositoryPort(Protocol):
    def create(self, application_id: UUID, org_id: UUID, identity_id: UUID, token_hash: str, expires_at) -> RefreshToken: ...

    def get_by_token_hash(self, token_hash: str) -> RefreshToken | None: ...

    def touch_last_used(self, refresh_token_id: UUID) -> None: ...


class ProfileRepositoryPort(Protocol):
    def create(self, org_id: UUID, name: str, *, is_admin: bool = False, **fields) -> Profile: ...

    def get(self, profile_id: UUID) -> Profile | None: ...

    def get_admin_profile(self, org_id: UUID) -> Profile | None: ...

    def list_by_org(self, org_id: UUID) -> list[Profile]: ...

    def update(self, profile_id: UUID, name: str, description: str | None) -> Profile: ...

    def delete(self, profile_id: UUID) -> None: ...

    def set_permissions(self, profile_id: UUID, permissions: list[str], granted_by: UUID | None) -> None: ...

    def list_permissions(self, profile_id: UUID) -> list[str]: ...
